apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 136314223160.dkr.ecr.us-east-1.amazonaws.com/docker-images-registry:frontend
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      imagePullSecrets: 
        - name: regcred

